### ISSUE TITLE
Decoding Issue. DREAM DRM

### ISSUE THREAD

**Issue by steven-bloom** [kit-cel/gr-drm#12]
Hallo, everyone!

DRM DREAM does not decode a signal, even from an audio cable.
I connected two computers via an audio cable. Headphone output with microphone input (PC with DRM DREAM)

I have installed with cmake../make/ sudo make install procedure. (UBUNTU 16.04. GNU RADIO 3.7.9)
A have attached Flowgraph and Screenshot of DREAM.
Can you help me, please?
Sincerely Yours
Timur
![screenshot from 2017-10-12 14-23-11](https://user-images.githubusercontent.com/30798903/31496192-a8273bac-af5a-11e7-9d29-c76ab5f8fee5.png)
![eff8-wn7ugi](https://user-images.githubusercontent.com/30798903/31496199-af6ab9a2-af5a-11e7-8018-39d410b78249.jpg)

**Comment by fwunsch** [comment]
Did you try by simply opening the file with DREAM? That always worked for me.

**Comment by steven-bloom** [comment]
Unfortunately that did not worked for me...

**Comment by fwunsch** [comment]
Well the wav files generated from the flow graph should be readable by dream, I just verified that. I'm using DREAM 2.1.1 and the latest master from gr-drm. Make sure your file source for the audio file is set to repeat=False as stopping the flow graph with Ctrl-C sometimes corrupts the wav file.

**Comment by steven-bloom** [comment]
Hallo, Felix!
I've just set Audio File Option Repeat=No and I was able to play the file in DREAM :+1: 
Thank you very much!
Ps Looking forward to try to transmit that File via Hackrf :)

**Comment by fwunsch** [comment]
Glad I could be of help ;)
