### ISSUE TITLE
object is not defined

### ISSUE THREAD

**Issue by oe2lsp** [kit-cel/gr-drm#9]
When I add a DRM-Block for example "DRM Configuration", I get following error message:
Value "drm.transm_params(2, 3, False, 0, 1, 0, 0 if 1==1 else 0, 0, 0, True, 24000, "GNU Radio on DRM", "This is GNU Radio on DRM!")" cannot be evaluated:
name 'drm' is not defined

I also installed grc on a new 16.04 Ubuntu, installed all updates, cmake, git and followed the description, endig up with the same error. grc-version 3.7.9

Maby I'm doing something wrong?

**Comment by fwunsch** [comment]
What do you mean by "adding" a DRM block?
Please make sure that your Python path is set and you did a "sudo ldconfig" after installing gr-drm.

**Comment by oe2lsp** [comment]
by "adding" I mean inserting a block from the library to the right of "GNU Radio Companion" from the Category "DRM"
The error message is displayed at the Properties of each DRM-Block, as well as marking the block with a read headline.

ldconfig -p | grep drm
	libva-drm.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libva-drm.so.1
	libgnuradio-drm.so (libc6,x86-64) => /usr/local/lib/libgnuradio-drm.so
	libfaad_drm.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libfaad_drm.so.2
	libdrm_radeon.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1
	libdrm_radeon.so.1 (libc6) => /usr/lib/i386-linux-gnu/libdrm_radeon.so.1
	libdrm_radeon.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_radeon.so
	libdrm_nouveau.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2
	libdrm_nouveau.so.2 (libc6) => /usr/lib/i386-linux-gnu/libdrm_nouveau.so.2
	libdrm_nouveau.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_nouveau.so
	libdrm_intel.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_intel.so.1
	libdrm_intel.so.1 (libc6) => /usr/lib/i386-linux-gnu/libdrm_intel.so.1
	libdrm_intel.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_intel.so
	libdrm_amdgpu.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1
	libdrm_amdgpu.so.1 (libc6) => /usr/lib/i386-linux-gnu/libdrm_amdgpu.so.1
	libdrm_amdgpu.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so
	libdrm.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm.so.2
	libdrm.so.2 (libc6) => /usr/lib/i386-linux-gnu/libdrm.so.2
	libdrm.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libdrm.so

is there anything else I can provide to help?

**Comment by fwunsch** [comment]
It looks to me like drm has not been imported, therefore "drm" is not known. Probably the import statement fails. And that may be due to the Python path not pointing to the right folders, hence my first comment. Did you check your Python path?

**Comment by oe2lsp** [comment]
which path at what moment do you think, the $PATH or ldconfig as shown above, at the end of the installation or at the moment of start?  
Is there any way I an debug this?

**Comment by fwunsch** [comment]
try "echo $PYTHONPATH". For me (Fedora) that is /usr/local/lib64/python2.7/site-packages, which is where a folder "drm" is located that contains the python interface.

**Comment by oe2lsp** [comment]
thank you for your answer, the variable was empty
I found the dictionary "drm" in /usr/local/lib/python2.7/dist-packages
so I set PYTHONPATH as shown above and startet gnuradio-companion in the same window, endig up with the same error message

**Comment by fwunsch** [comment]
If you used export to set the PYTHONPATH, did you make sure to start GRC from the same shell?

**Comment by oe2lsp** [comment]
when executing `make test` 
test 2 to 13 were failing

as going deeper into debugging with 'ctest -V'
the log (build/Testing/Temporary/LastTest.log) shows nearly the same output for each case:
'2/13 Testing: qa_scrambler_bb
2/13 Test: qa_scrambler_bb
Command: "/bin/sh" "/home/spel/Downloads/drm/gr-drm/build/python/qa_scrambler_bb_test.sh"
Directory: /home/spel/Downloads/drm/gr-drm/build/python
"qa_scrambler_bb" start time: Jun 05 22:54 CEST
Output:
----------------------------------------------------------
Traceback (most recent call last):
  File "/home/spel/Downloads/drm/gr-drm/python/qa_scrambler_bb.py", line 24, in <module>
    import drm_swig as drm
ImportError: No module named drm_swig
<end of output>
Test time =   0.24 sec
----------------------------------------------------------
Test Failed.'


in the end I solved the problem by installing 'swig3.0'

thank you for your help
